site_name: Software Development Notes

nav:
    - Overview: 'index.md'
    - Ubuntu: 'ubuntu.md'
    - Git: 'git.md'
    - Python: 'py.md'
    - Network: 'network.md'
    - Fish: 'fish.md'
    - Shell: 'shell.md'
    - Docker: 'docker.md'
    - API's: 'apis.md'
    # - Databases: 'databases.md'




theme:
    name: material
    icon:
        logo: material/reminder
    # :material-reminder:
    # logo: assets/rice_48.png
    favicon: ./images/ic_reminder_black_18dp.png
    features:
        - navigation.instant
        - navigation.tracking
        - navigation.tabs
        - navigation.tabs.sticky
    palette:
        primary: 'cyan'
        accent: 'amber'

repo_name: dev-notes
repo_url:
docs_dir: dev_notes


markdown_extensions:
    - toc:
        permalink: 💡
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.tabbed
    - pymdownx.superfences
    - admonition
    - attr_list

extra_css:
    - 'css/custom.css'

