name: Publish to Netlify on push to main

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ['3.8']
        node-version: ['15.x']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python_version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements_actions.txt ]; then pip install -r requirements_actions.txt; fi
        pip install .
    - name: Build site
      run: mkdocs build --clean --site-dir public
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install netlify cli
      run: npm install netlify-cli -g
    - name: Deploy the site with netlify-cli
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      run: netlify deploy --dir=public --prod
